# Generated by Django 6.0.2 on 2026-02-21 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(choices=[('Comportamento', 'Comportamento'), ('Entregas', 'Entregas'), ('Trabalho em equipe', 'Trabalho em equipe')], max_length=50, verbose_name='Dimensão')),
                ('tipo_item_avaliacao_desempenho', models.CharField(max_length=255, verbose_name='Tipo de item')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Item de Avaliação',
                'verbose_name_plural': 'Tipos de Item de Avaliação',
                'ordering': ['dimensao', 'tipo_item_avaliacao_desempenho'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_competencia', models.DateField(verbose_name='Mês de competência')),
                ('status_avaliacao', models.CharField(choices=[('Criada', 'Criada'), ('Em elaboração', 'Em elaboração'), ('Em avaliação', 'Em avaliação'), ('Concluída', 'Concluída')], default='Criada', max_length=20, verbose_name='Status')),
                ('nota', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota')),
                ('sugestoes_supervisor', models.TextField(blank=True, default='', verbose_name='Sugestões do supervisor')),
                ('observacoes_avaliado', models.TextField(blank=True, default='', verbose_name='Observações do avaliado')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='avaliacao.colaborador', verbose_name='Colaborador')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_supervisionadas', to='avaliacao.colaborador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Desempenho',
                'ordering': ['-mes_competencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='avaliacao.avaliacaodesempenho', verbose_name='Avaliação de desempenho')),
                ('tipo_item_avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='avaliacao.tipoitemavaliacaodesempenho', verbose_name='Tipo de item')),
            ],
            options={
                'verbose_name': 'Item de Avaliação',
                'verbose_name_plural': 'Itens de Avaliação',
                'ordering': ['tipo_item_avaliacao_desempenho'],
            },
        ),
        migrations.AddConstraint(
            model_name='avaliacaodesempenho',
            constraint=models.UniqueConstraint(fields=('colaborador', 'mes_competencia'), name='unique_colaborador_mes_competencia'),
        ),
    ]
